import sqlite3
import os

print(os.getcwd(), "------------")

conn = sqlite3.connect("instance/easyGrade.db")
print("Opened database successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS MAESTROS
        (MAESTRO_ID INTEGER PRIMARY KEY NOT NULL,
        NOMBRE VARCHAR NOT NULL,
        APELLIDO VARCHAR NOT NULL,
        MATERIA_ID INTEGER,
        CONTACTO_ID INTEGER,
        PASSWORD_ID VARCHAR NOT NULL,
        FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(ID),
        FOREIGN KEY (CONTACTO_ID) REFERENCES CONTACTOS(ID),
        FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORDS(ID))"""
)
print("Table MAESTROS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CONTACTOS
        (CONTACTO_ID INTEGER PRIMARY KEY NOT NULL,
        TELEFONO VARCHAR,
        DIRECCION VARCHAR,
        CORREO_ELECTRONICO VARCHAR NOT NULL);"""
)
print("Table CONTACTOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS MATERIAS
        (ID INTEGER PRIMARY KEY NOT NULL,
        NOMBRE VARCHAR NOT NULL,
        NIVEL VARCHAR NOT NULL);"""
)
print("Table MATERIAS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS ALUMNOS
         (ALUMNO_ID INTEGER PRIMARY KEY NOT NULL,
         NOMBRE VARCHAR NOT NULL,
         APELLIDO VARCHAR NOT NULL,
         FECHA_NACIMIENTO DATE,
         MATERIA_ID INTEGER NOT NULL,
         PASSWORD_ID VARCHAR NOT NULL,
         CONTACTO_ID VARCHAR NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
         FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORDS(PASSWORD_ID),
         FOREIGN KEY (CONTACTO_ID) REFERENCES CONTACTOS(CONTACTO_ID));"""
)
print("Table ALUMNOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS EJERCICIOS
         (EJERCICIOS_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION VARCHAR NOT NULL,
         QUESTION VARCHAR NOT NULL,
         ANSWER VARCHAR NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID));"""
)
print("Table EJERCICIOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS PASSWORDS
         (PASSWORD_ID INTEGER PRIMARY KEY NOT NULL,
         PASSWORD VARCHAR NOT NULL);"""
)
print("Table PASSWORDS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS TAREAS
         (TAREAS_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION TEXT NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         ALUMNO_ID INTEGER NOT NULL,
         MAESTRO_ID INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
         FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID),
         FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID));"""
)
print("Table TAREAS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS EXAMENES
         (EXAMENES_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION TEXT NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         ALUMNO_ID INTEGER NOT NULL,
         MAESTRO_ID INTEGER NOT NULL,
         CALIFICACION INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
         FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID),
         FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID));"""
)
print("Table EXAMENES created successfully")

conn.close()
